### ISSUE TITLE
Unclear information on CSL2XSB 

### ISSUE THREAD

**Issue by crazytimtimtim** [TwinFan/XPMP2#38]
Sorry for posting this as an issue, it's more of a question.

On this repo you say we need to run the CSL2XSB.py script to convert X-CSL models to get all functionality, but on the CSL2XSB xplane forum page, you write that it is unnecessary.

So, I understand I can use XPMP2-based plugins without the python script, but will I have _full_ functionality?

Thanks!

**Comment by TwinFan** [comment]
Using `CSL2XSB-py` is no longer required. The full functionality is built inside of XPMP2 (see [here](https://twinfan.github.io/XPMP2/CopyingObjFiles.html) for details). You aren't missing anything.

I removed the outdated recommendation from the README file. Is there any other trace left?

**Comment by crazytimtimtim** [comment]
Sorry for the late response. I don't see any references right now but will let you know if I do.
